# Generated by Django 5.0.2 on 2024-03-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
